backup from a spec file defining the target system

diff --git a/lrc-clone b/lrc-clone
--- a/lrc-clone
+++ b/lrc-clone
@@ -1,16 +1,16 @@
 #!/usr/bin/env bash
 
 if test -z "$1" ; then
-    echo "usage: $0 backup-destination-dev" >&2
+    echo "usage: $0 spec-file" >&2
     exit 1
 fi
 
 set -u
+set -e
+#set -x
 
-BOOTDEV=$(cat $1 | sed 's/[ \t]\+$//g' | grep 'boot-loader$' | sed 's/[ \t]\+/ /g' | cut -d\  -f1)
-PART=${BOOTDEV}1
-TMNT=
-MNT=
+SPEC=$1
+BOOTDEV=$(cat $SPEC | sed 's/[ \t]\+$//g' | grep 'boot-loader$' | sed 's/[ \t]\+/ /g' | cut -d\  -f1)
 
 PATH=/usr/sbin:/sbin:$PATH
 
@@ -32,61 +32,60 @@ second-guess () {
 	fi
 }
 
-mount-device () {
-	MNT=$(cat /proc/mounts | grep $PART | cut -d\  -f2)
-	if (( $? == 0 )) ; then
-		TMNT=$(mktemp -d /tmp/backup/dst.XXXXX)
-		MNT=$TMNT
-		mkdir -p $MNT || die "unable to mkdir $MNT"
-		mount $PART $MNT || die "unable to mount $PART on $MNT"
-	fi
-	echo "$PART mounted on $MNT"
-}
-
 trim-comments () {
 	sed 's/#.*$//g' | sed 's/[ \t]*$//g' | grep -v "^$"
 }
 
-trim-fstab () {
-	cat /etc/fstab | trim-comments | awk '{printf "%s %s %s\n", $1, $2, $3}'
+trimfile () {
+	cat $1 | trim-comments | awk '{printf "%s %s %s\n", $1, $2, $3}'
 }
 
 clone-fs () {
-	local SRC=$(mktemp -d /tmp/backup/src.XXXXX)
 
+	DST=$(mktemp -d /tmp/backup/dst.XXXXX)
+	while read dev mnt rest ; do
+		if [ "$mnt" != "boot-loader" ] ; then
+			mkdir -p $DST${mnt}
+			run-cmd "mount $dev $DST${mnt}"
+		fi
+	done < <(LC_ALL=C trimfile $SPEC | sort -k2)
+
+	local SRC=$(mktemp -d /tmp/backup/src.XXXXX)
 	# remount everything in fstab on a temporary mount point
 	while read dev mnt fs rest ; do
-		if [ "$mnt" != "none" ] ; then
+		if [ "$dev" != "none" ] ; then
 			run-cmd "mount $dev $SRC${mnt}"
 		fi
-	done < <(LC_ALL=C trim-fstab | sort -k2) # LC_ALL is so sort doesn't ignore '/' characters
+	done < <(LC_ALL=C trimfile /etc/fstab | sort -k2)
 
 	# rsync the temporary mount point SRC to the target device
-	echo "cloning $SRC to $MNT..."
+	echo "cloning $SRC to $DST"
 	rsync -aEHSv --delete --exclude tmp \
 		$SRC/* \
-		$MNT/. || die "rsync failed"
-	mkdir -p $MNT/tmp
+		$DST/. || die "rsync failed"
+	mkdir -p $DST/tmp
 
 	# umount everything in the temporary mount point (in reverse order with sort -r)
 	while read dev mnt fs rest ; do
-		if [ "$mnt" != "none" ] ; then
+		if [ "$dev" != "none" ] ; then
 			run-cmd "umount $SRC${mnt}"
 		fi
-	done < <(LC_ALL=C trim-fstab | sort -r -k2) # LC_ALL is so sort doesn't ignore '/' characters
-
+	done < <(LC_ALL=C trimfile /etc/fstab | sort -r -k2)
 	rmdir $SRC
+
 }
 
 rewrite-grub () {
 	echo "installing GRUB2 on $BOOTDEV"
 
 	for d in dev proc run sys ; do
-		mkdir -p $MNT/$d
-		mount --bind /$d $MNT/$d || die "failed to mount --bind /$d $MNT/$d"
+		mkdir -p $DST/$d
+		mount --bind /$d $DST/$d || die "failed to mount --bind /$d $DST/$d"
 	done
 
-cat << EOF > $MNT/etc/default/grub
+	mkdir -p $DST/etc/default
+
+cat << EOF > $DST/etc/default/grub
 GRUB_DEFAULT=0
 GRUB_TIMEOUT=20
 #GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo "Reuben Reboot Lunux Backup"`
@@ -95,7 +94,7 @@ GRUB_DISTRIBUTOR="Reuben Reboot Lunux Backup"
 GRUB_CMDLINE_LINUX=""
 EOF
 
-cat << EOF > $MNT/tmp/grub.sh
+cat << EOF > $DST/tmp/grub.sh
 #!/usr/bin/env bash
 sed -i 's/GRUB_TIMEOUT=.*$/GRUB_TIMEOUT=30/g' /etc/default/grub
 echo GRUB_DISABLE_OS_PROBER=true >> /etc/default/grub
@@ -103,22 +102,23 @@ grub-install $BOOTDEV
 update-grub
 EOF
 
-	chmod +x $MNT/tmp/grub.sh
+	chmod +x $DST/tmp/grub.sh
 	(
-		chroot $MNT /tmp/grub.sh
+		chroot $DST /tmp/grub.sh
 	)
-	rm $MNT/tmp/grub.sh
+	rm $DST/tmp/grub.sh
 
 	for d in dev proc run sys ; do
-		umount $MNT/$d
+		umount $DST/$d
 	done
 }
 
 rewrite-fstab () {
-	echo "writing new $MNT/etc/fstab..."
-	local UUID=$(blkid $PART | cut -d\" -f2)
+	echo "writing new $DST/etc/fstab..."
 
-cat << EOF > $MNT/etc/fstab
+	mkdir -p $DST/etc
+
+cat << EOF > $DST/etc/fstab
 # /etc/fstab: static file system information.
 #
 # Use 'blkid' to print the universally unique identifier for a
@@ -126,26 +126,45 @@ cat << EOF > $MNT/etc/fstab
 # that works even if disks are added and removed. See fstab(5).
 #
 # <file system> <mount point>   <type>  <options>       <dump>  <pass>
-UUID=$UUID / auto errors=remount-ro 0 1
+EOF
+
+	while read dev mnt rest ; do
+		if [ "$mnt" != "boot-loader" ] ; then
+			local UUID=$(blkid $dev| cut -d\" -f2)
+			if [ "$mnt" = "/" ] ; then
+				pass=1
+			else
+				pass=0
+			fi
+
+cat << EOF >> $DST/etc/fstab
+UUID=$UUID $mnt auto errors=remount-ro 0 $pass
+EOF
+		fi
+	done < <(LC_ALL=C trimfile $SPEC | sort -r -k2)
+
+cat << EOF >> $DST/etc/fstab
 none /tmp tmpfs defaults 0 0
 EOF
 
-}
-
-cleanup () {
-	if [ "$TMNT" != "" ] ; then
-		umount $TMNT && rmdir $TMNT
-	fi
+	cat $DST/etc/fstab
 }
 
 main () {
 	mkdir -p /tmp/backup
 	second-guess
-	mount-device
 	clone-fs
 	rewrite-fstab
-	rewrite-grub
-	cleanup
+	#rewrite-grub
+
+	while read dev mnt rest ; do
+		if [ "$mnt" != "boot-loader" ] ; then
+			run-cmd "umount $DST${mnt}"
+		fi
+	done < <(LC_ALL=C trimfile $SPEC | sort -r -k2)
+sleep 1
+	rmdir $DST
+	rmdir /tmp/backup
 }
 
 main
